name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v4
    
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -
                name: Set environment variables
                run: |
                    rm -rf .env
                    echo "PUBLIC_APP_ENV=${{ secrets.PUBLIC_APP_ENV }}" >> .env
                    echo "PUBLIC_SENTRY_DSN=${{ secrets.PUBLIC_SENTRY_DSN }}" >> .env
                    echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
                    echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
                    echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
                    echo "JWT_SESSION_SECRET=${{ secrets.JWT_SESSION_SECRET }}" >> .env
                    echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
                    echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
                    echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
                    echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env

            -
                name: Build docker image
                run: |
                    docker build . -t iamthewraith/buzybee:latest
            
            -
                name: Push docker image
                run: |
                    docker push iamthewraith/buzybee:latest                 

            -
                name: copy docker-compose file to vps
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_HOST}}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY}}
                    port: ${{ secrets.SSH_PORT }}
                    source: "docker-compose.yaml"
                    target: ${{ secrets.SSH_TARGET }}

            -
                name: restart docker-compose
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_HOST}}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY}}
                    port: ${{ secrets.SSH_PORT }}
                    script: |
                        cd ${{ secrets.SSH_TARGET }}
                        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                        docker compose down --rmi all --volumes --remove-orphans
                        docker compose up -d